//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_IPET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.CommentImagePaths = new HashSet<CommentImagePath>();
        }
    
        public int CommentID { get; set; }
        public int MemberID { get; set; }
        public int ProductID { get; set; }
        public int OrderDetailID { get; set; }
        public int Rating { get; set; }
        public string CommentContent { get; set; }
        public System.DateTime CommentDate { get; set; }
        public bool Banned { get; set; }
        public string BannedContent { get; set; }
        public Nullable<int> CommentReplyID { get; set; }
        public string ReplyContent { get; set; }
        public bool Reply { get; set; }
    
        public virtual CommentReply CommentReply { get; set; }
        public virtual Member Member { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentImagePath> CommentImagePaths { get; set; }
    }
}
