//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_IPET
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyFavorite
    {
        public int FavoriteID { get; set; }
        public int FavoriteType { get; set; }
        public int ProductID { get; set; }
        public int MemberID { get; set; }
    
        public virtual FavoriteType FavoriteType1 { get; set; }
        public virtual Member Member { get; set; }
        public virtual Product Product { get; set; }
    }
}
