//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_IPET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notify
    {
        public int NotifyID { get; set; }
        public string NotifyContent { get; set; }
        public int NotifyTypeID { get; set; }
        public int MemberID { get; set; }
        public bool ReadStatus { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual NotifiesType NotifiesType { get; set; }
    }
}
