//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_IPET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pet()
        {
            this.PetImagePaths = new HashSet<PetImagePath>();
        }
    
        public int PetID { get; set; }
        public string PetVariety { get; set; }
        public int PetCategoryID { get; set; }
        public bool PetGender { get; set; }
        public int PetSize { get; set; }
        public int PetColor { get; set; }
        public int PetAge { get; set; }
        public int PetFix { get; set; }
        public int PetCityID { get; set; }
        public int PetRegionID { get; set; }
        public string PetDescription { get; set; }
        public int PetImagePathID { get; set; }
        public string PetContact { get; set; }
        public string PetContactPhone { get; set; }
    
        public virtual PetImagePath PetImagePath { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PetImagePath> PetImagePaths { get; set; }
    }
}
